using Dapper;
using Oracle.ManagedDataAccess.Client;

// 接続文字列
// SYSユーザーとして接続する場合は、SYSDBAまたはSYSOPERの権限を指定する必要があります。
// 接続文字列に DBA Privilege=SYSDBA を含めることで、SYSDBA権限で接続します。
string connectionString = "User Id=sys;Password=passw0rd;DBA Privilege=SYSDBA;Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=XE)));";

// DB接続
using OracleConnection db = new(connectionString);

// テーブルの作成または初期化
CreateOrTruncateTable(db);

// データの挿入
InsertData(db, "John Doe", 30);
InsertData(db, "Hoge Fuga", 25);
InsertData(db, "Piyo Piyo", 20);

// データの選択と表示
Console.WriteLine("Initial Data:");
DisplayData(db);

// データの更新
Console.WriteLine("Update Data:");
UpdateData(db, "UPDATEEEEEEEEEEEEEEE", 35);

// データの再選択と表示
DisplayData(db);

// データの削除
Console.WriteLine("Delete Data:");
DeleteData(db);

// データの再選択と表示
DisplayData(db);



/// <summary>
/// テーブルの作成または初期化
/// </summary>
/// <param name="db"></param>
void CreateOrTruncateTable(OracleConnection db)
{
    var createTableQuery = """
        DECLARE
            table_count INTEGER;
        BEGIN
            SELECT COUNT(*) INTO table_count FROM user_tables WHERE table_name = 'SAMPLETABLE';
            IF table_count = 0 THEN
                EXECUTE IMMEDIATE 'CREATE TABLE SampleTable (
                    Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    Name VARCHAR2(100),
                    Age NUMBER
                )';
            ELSE
                EXECUTE IMMEDIATE 'TRUNCATE TABLE SampleTable';
            END IF;
        END;
        """;
    db.Execute(createTableQuery);
}

/// <summary>
/// データの挿入
/// </summary>
/// <param name="db"></param>
/// <param name="name"></param>
/// <param name="age"></param>
void InsertData(OracleConnection db, string name, int age)
{
    var insertQuery = "INSERT INTO SampleTable (Name, Age) VALUES (:Name, :Age)";
    db.Execute(insertQuery, new { Name = name, Age = age });
}

/// <summary>
/// データの表示
/// </summary>
/// <param name="db"></param>
void DisplayData(OracleConnection db)
{
    var selectQuery = "SELECT * FROM SampleTable";
    var data = db.Query<SampleTable>(selectQuery);
    foreach (var item in data)
    {
        Console.WriteLine($"ID: {item.Id}, Name: {item.Name}, Age: {item.Age}");
    }
}

/// <summary>
/// データの更新
/// </summary>
/// <param name="db"></param>
/// <param name="name"></param>
/// <param name="age"></param>
void UpdateData(OracleConnection db, string name, int age)
{
    var selectQuery = "SELECT * FROM SampleTable";
    var data = db.Query<SampleTable>(selectQuery);
    var updateID = data.First().Id;
    var updateQuery = "UPDATE SampleTable SET Name = :Name, Age = :Age WHERE ID = :id";
    db.Execute(updateQuery, new { ID = updateID, Name = name, Age = age });
}

/// <summary>
/// データの削除
/// </summary>
/// <param name="db"></param>
void DeleteData(OracleConnection db)
{
    var selectQuery = "SELECT * FROM SampleTable";
    var data = db.Query<SampleTable>(selectQuery);
    var deleteID = data.Last().Id;
    var deleteQuery = "DELETE FROM SampleTable WHERE ID = :id";
    db.Execute(deleteQuery, new { ID = deleteID });
}

public class SampleTable
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public int Age { get; set; }
}
